### ISSUE TITLE
Shutter responses are missing the leading ':'

### ISSUE THREAD

**Issue by rpineau** [nexdome/Firmware#2]
The current 3.0.0 firmware, when responding to shutter commands, is missing the leading ':' in the response.

**Comment by NameOfTheDragon** [comment]
This capture from PuTTY illustrates the problem:

> XB->Online
> @RRR
> :RRR55080#
> @RRS
> RRS46000
> XB->Online

The ASCOM driver is not affected, but this is a confirmed bug.

**Comment by NameOfTheDragon** [comment]
Fixed in PR #5 (hex files can be found in the PR if you;d like to try them)

**Comment by NameOfTheDragon** [comment]
Merged into develop, this will be in the next release.
